# AWSTemplateFormatVersion: "2010-09-09"
# Resources:
#   MyEC2Instance:
#     Type: "AWS::EC2::Instance"
#     Properties: 
#       InstanceType: "t2.micro"
#       ImageId: "ami-0182f373e66f89c85" 
      # KeyName: "my-key-pair"  
      # SecurityGroupIds: 
      #   - !Ref MySecurityGroup
      # UserData: 
      #   Fn::Base64: 
      #     !Sub |
      #       #!/bin/bash
      #       yum update -y
      #       amazon-linux-extras install docker
      #       service docker start
      #       usermod -a -G docker ec2-user
      #       docker pull ojunwoo/my-app:latest
      #       docker run -d -p 80:80 my-app:latest

  # MySecurityGroup:
  #   Type: "AWS::EC2::SecurityGroup"
  #   Properties:
  #     GroupDescription: "Enable SSH and HTTP access"
  #     SecurityGroupIngress:
  #       - IpProtocol: tcp
  #         FromPort: 22
  #         ToPort: 22
  #         CidrIp: 0.0.0.0/0
  #       - IpProtocol: tcp
  #         FromPort: 80
  #         ToPort: 80
  #         CidrIp: 0.0.0.0/0


AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Resources:
  MyEC2Instance: #An inline comment
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-0ff8a91507f77f867" #Another comment -- This is a Linux AMI
      InstanceType: t2.micro
      KeyName: testkey
      BlockDeviceMappings:
        -
          DeviceName: /dev/sdm
          Ebs:
            VolumeType: io1
            Iops: 200
            DeleteOnTermination: false
            VolumeSize: 20
